name: flavorag-app

services:
  server:
    build: ../flavorag-server
    ports:
      - "9090:9090"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    build: ../flavorag-frontend
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flavorag
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    command: redis-server --requirepass 123456
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
